## Pandas Practice

In [0]:
import pandas as pd

In [0]:
path = "/Workspace/Users/guruvendra47@gmail.com/Learn_coding/customer_data.csv"

df = pd.read_csv(path)
df

    customer_id           name   age  ... signup_date purchase_amount  membership
0           101    Alice Smith  25.0  ...  2023-01-15          250.50        Gold
1           102      bob jones  34.0  ...  2023-02-20           89.00      silver
2           103  Charlie Brown   NaN  ...  2023/03/10          430.00        Gold
3           104      David Lee  45.0  ...  2023-04-05             NaN      Bronze
4           105      Eva Green  29.0  ...  2023-05-18          120.75      Silver
5           106    Frank White  52.0  ...  2023-01-22          310.00        gold
6           107      Grace Kim  31.0  ...  2023-06-30           45.50      Bronze
7           108     Henry Ford  40.0  ...  2023-07-14          999.99        Gold
8           109       Ivy Chen  27.0  ...  2023-08-09           76.00      Silver
9           110     Jack Black  38.0  ...  2023-09-01          205.25      Bronze
10          111     Karen Hill  60.0  ...  2023-02-11          150.00        Gold
11          112      Leo Young  22.0  ...  2023-03-25             NaN      Silver
12          113       Mona Rao   NaN  ...  2023-04-19           60.00      Bronze
13          102      bob jones  34.0  ...  2023-02-20           89.00      silver
14          115     Nina Patel  33.0  ...  2023-05-05          410.00        Gold
15          116     Oscar Diaz  41.0  ...  2023-06-17           33.50      Bronze
16          117    Pam Beasley  29.0  ...  2023-07-28          220.00      Silver
17          118      Quinn Fox  37.0  ...  2023-08-22          175.25        Gold
18          119      Rita Shah  26.0  ...  2023-09-30          500.00      Bronze
19          120     Sam Wilson  48.0  ...  2023-10-10           95.00      Silver
20          121            NaN  55.0  ...  2023-01-05          310.00        Gold
21          122       Tina Ray  31.0  ...  2023-02-15           48.00      Bronze
22          123      Umar Khan   NaN  ...  2023-03-18          630.00      Silver
23          124      Vera Lane  44.0  ...  2023-04-22             NaN        Gold
24          125     Will Scott  39.0  ...  2023-05-29          112.50      Bronze
25          126      Xena Cruz  28.0  ...  2023-06-08          275.00      Silver
26          127      Yara Nasr  36.0  ...  2023-07-19           88.00        Gold
27          128      Zane Cole  50.0  ...  2023-08-25          345.00      Bronze
28          129        Amy Liu  24.0  ...  2023-09-14           59.99      Silver
29          130     Ben Carter  32.0  ...  2023-10-01          410.00        Gold
30          104      David Lee  45.0  ...  2023-04-05             NaN      Bronze

[31 rows x 7 columns]

In [0]:
# to check all the columns
pd.set_option("display.max_columns", None)
display(df)

customer_id,name,age,city,signup_date,purchase_amount,membership
101,Alice Smith,25.0,Toronto,2023-01-15,250.5,Gold
102,bob jones,34.0,toronto,2023-02-20,89.0,silver
103,Charlie Brown,null,Vancouver,2023/03/10,430.0,Gold
104,David Lee,45.0,Montreal,2023-04-05,null,Bronze
105,Eva Green,29.0,Calgary,2023-05-18,120.75,Silver
106,Frank White,52.0,Toronto,2023-01-22,310.0,gold
107,Grace Kim,31.0,Ottawa,2023-06-30,45.5,Bronze
108,Henry Ford,40.0,Vancouver,2023-07-14,999.99,Gold
109,Ivy Chen,27.0,Montreal,2023-08-09,76.0,Silver
110,Jack Black,38.0,Calgary,2023-09-01,205.25,Bronze
111,Karen Hill,60.0,Toronto,2023-02-11,150.0,Gold
112,Leo Young,22.0,Vancouver,2023-03-25,null,Silver
113,Mona Rao,null,Ottawa,2023-04-19,60.0,Bronze
102,bob jones,34.0,toronto,2023-02-20,89.0,silver
115,Nina Patel,33.0,Calgary,2023-05-05,410.0,Gold
116,Oscar Diaz,41.0,Montreal,2023-06-17,33.5,Bronze
117,Pam Beasley,29.0,Toronto,2023-07-28,220.0,Silver
118,Quinn Fox,37.0,Vancouver,2023-08-22,175.25,Gold
119,Rita Shah,26.0,Ottawa,2023-09-30,500.0,Bronze
120,Sam Wilson,48.0,Calgary,2023-10-10,95.0,Silver
121,null,55.0,Toronto,2023-01-05,310.0,Gold
122,Tina Ray,31.0,Montreal,2023-02-15,48.0,Bronze
123,Umar Khan,null,Vancouver,2023-03-18,630.0,Silver
124,Vera Lane,44.0,Ottawa,2023-04-22,null,Gold
125,Will Scott,39.0,Toronto,2023-05-29,112.5,Bronze
126,Xena Cruz,28.0,Calgary,2023-06-08,275.0,Silver
127,Yara Nasr,36.0,Vancouver,2023-07-19,88.0,Gold
128,Zane Cole,50.0,Montreal,2023-08-25,345.0,Bronze
129,Amy Liu,24.0,Toronto,2023-09-14,59.99,Silver
130,Ben Carter,32.0,Ottawa,2023-10-01,410.0,Gold
104,David Lee,45.0,Montreal,2023-04-05,null,Bronze

In [0]:
df.head(5)

,customer_id,name,age,city,signup_date,purchase_amount,membership
0,101,Alice Smith,25.0,Toronto,2023-01-15,250.50,Gold
1,102,bob jones,34.0,toronto,2023-02-20,89.00,silver
2,103,Charlie Brown,NaN,Vancouver,2023/03/10,430.00,Gold
3,104,David Lee,45.0,Montreal,2023-04-05,NaN,Bronze
4,105,Eva Green,29.0,Calgary,2023-05-18,120.75,Silver

In [0]:
df.tail(5)

,customer_id,name,age,city,signup_date,purchase_amount,membership
26,127,Yara Nasr,36.0,Vancouver,2023-07-19,88.00,Gold
27,128,Zane Cole,50.0,Montreal,2023-08-25,345.00,Bronze
28,129,Amy Liu,24.0,Toronto,2023-09-14,59.99,Silver
29,130,Ben Carter,32.0,Ottawa,2023-10-01,410.00,Gold
30,104,David Lee,45.0,Montreal,2023-04-05,NaN,Bronze

In [0]:
df.shape

(31, 7)

In [0]:
df.dtypes

customer_id          int64
name                object
age                float64
city                object
signup_date         object
purchase_amount    float64
membership          object
dtype: object

1. singup_Date has wrong data type
2. age should be intger not float

In [0]:
df.describe()

       customer_id        age  purchase_amount
count    31.000000  28.000000        27.000000
mean    114.741935  36.964286       242.156667
std       9.204954   9.953530       219.821913
min     101.000000  22.000000        33.500000
25%     106.500000  29.000000        88.500000
50%     115.000000  35.000000       175.250000
75%     122.500000  44.250000       327.500000
max     130.000000  60.000000       999.990000

In [0]:
df.columns

Index(['customer_id', 'name', 'age', 'city', 'signup_date', 'purchase_amount',
       'membership'],
      dtype='object')

In [0]:
# columns names are good no need to change reanme anything 
df = df.rename(columns={"customer_id":"CustomerID"})
df.columns

Index(['CustomerID', 'name', 'age', 'city', 'signup_date', 'purchase_amount',
       'membership'],
      dtype='object')

In [0]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerID       31 non-null     int64
 1   name             30 non-null     object
 2   age              28 non-null     float64
 3   city             31 non-null     object
 4   signup_date      31 non-null     object
 5   purchase_amount  27 non-null     float64
 6   membership       31 non-null     object
dtypes: float64(2), int64(1), object(4)
memory usage: 1.8+ KB

In [0]:
# find the duplicates now
df.duplicated().sum()
df[df.duplicated()]

,CustomerID,name,age,city,signup_date,purchase_amount,membership
13,102,bob jones,34.0,toronto,2023-02-20,89.0,silver
30,104,David Lee,45.0,Montreal,2023-04-05,NaN,Bronze